const API = '/api';
let token = localStorage.getItem('rp_token');
let user = JSON.parse(localStorage.getItem('rp_user') || 'null');
let settings = null;
let materials = [];
let aiItems = [];

const $ = id => document.getElementById(id);
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hide');setTimeout(()=>$('toast').classList.add('hide'),3500)}
async function api(path, opts={}){
  const res = await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}});
  const data = await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(data.error || 'Error');
  return data;
}
function money(n){return '$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function bs(n){return 'Bs '+Number(n||0).toLocaleString('es-VE',{minimumFractionDigits:2,maximumFractionDigits:2})}
function isAdmin(){return user && ['superadmin','admin'].includes(user.role)}
function roleLabel(r){return {superadmin:'Súper administrador',admin:'Administrador',rotulador:'Rotulador / Vendedor'}[r]||r}

$('loginTab').onclick=()=>{ $('loginForm').classList.remove('hide'); $('registerForm').classList.add('hide'); $('loginTab').classList.add('active'); $('registerTab').classList.remove('active') };
$('registerTab').onclick=()=>{ $('registerForm').classList.remove('hide'); $('loginForm').classList.add('hide'); $('registerTab').classList.add('active'); $('loginTab').classList.remove('active') };
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});token=d.token;user=d.user;localStorage.setItem('rp_token',token);localStorage.setItem('rp_user',JSON.stringify(user));boot()}catch(err){toast(err.message)}};
$('registerForm').onsubmit=async e=>{e.preventDefault();try{await api('/auth/register',{method:'POST',body:JSON.stringify({name:$('regName').value,phone:$('regPhone').value,email:$('regEmail').value,password:$('regPassword').value,requestedRole:$('regRole').value})});toast('Solicitud enviada. Revisa aprobación del administrador.');$('loginTab').click();e.target.reset()}catch(err){toast(err.message)}};
function logout(){localStorage.clear();token=null;user=null;$('app').classList.add('hide');$('auth').classList.remove('hide')}
async function boot(){if(!token||!user)return;$('auth').classList.add('hide');$('app').classList.remove('hide');$('roleText').textContent=roleLabel(user.role);buildNav();await loadSettings();show('dashboard')}
function buildNav(){const items=[['dashboard','Inicio'],['quote','Nueva cotización'],['orders','Órdenes y ventas']];if(isAdmin())items.push(['users','Usuarios'],['settings','Precios y configuración']);$('nav').innerHTML=items.map(i=>`<button id="nav-${i[0]}" onclick="show('${i[0]}')">${i[1]}</button>`).join('')}
async function loadSettings(){const d=await api('/settings');settings=d.settings;materials=d.materials}
async function show(view){document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));$('nav-'+view)?.classList.add('active');if(view==='dashboard')return dashboard();if(view==='quote')return quote();if(view==='orders')return orders();if(view==='users')return users();if(view==='settings')return config()}
function title(t,s){$('title').textContent=t;$('subtitle').textContent=s}
async function dashboard(){title('Inicio','Ofertas, órdenes pendientes, diseños aprobados e instalaciones programadas.');const ord=await api('/orders');const sales=ord.reduce((a,o)=>a+Number(o.price_usd||0),0);const profit=ord.reduce((a,o)=>a+(Number(o.price_usd||0)-Number(o.internal_cost||0)),0);$('content').innerHTML=`<div class="grid"><div class="card stat"><small>Ofertas disponibles</small><strong>3</strong><span>Promos activas</span></div><div class="card stat"><small>Órdenes pendientes</small><strong>${ord.filter(o=>!['Finalizado','Cancelado'].includes(o.status)).length}</strong></div><div class="card stat"><small>Diseños aprobados</small><strong>${ord.filter(o=>o.status==='Diseño aprobado').length}</strong></div><div class="card stat"><small>Instalaciones programadas</small><strong>${ord.filter(o=>o.status==='Instalación programada').length}</strong></div>${isAdmin()?`<div class="card stat"><small>Ventas</small><strong>${money(sales)}</strong></div><div class="card stat"><small>Ganancia</small><strong>${money(profit)}</strong></div>`:''}<div class="card stat"><small>Euro BCV</small><strong>${Number(settings.euro_bcv_rate).toFixed(2)}</strong></div><div class="card wide"><h2>Acciones rápidas</h2><button onclick="show('quote')">Nueva cotización</button> ${isAdmin()?'<button class="ghost" onclick="updateBcv()">Actualizar Euro BCV</button>':''}</div></div>`}
async function updateBcv(){try{const d=await api('/rates/bcv/euro/update',{method:'POST'});settings=d.settings;toast('Tasa actualizada: '+d.rate.rate);dashboard()}catch(e){toast(e.message)}}
function quote(){title('Nueva cotización','Cotizador con IA, USD/Bs y registro de venta.');aiItems=[];$('content').innerHTML=`<div class="quote"><section class="card full"><h2>Datos de venta</h2><div class="grid"><div class="card side"><label>Cliente</label><input id="client_name"><label>Teléfono</label><input id="client_phone"><label>Negocio</label><input id="business_name"><label>Tipo de venta</label><select id="sale_type"><option>Rotulación de carro</option><option>Rotulación de moto</option><option>Sticker</option><option>Calcomanía</option><option>Kit de moto</option><option>Publicidad</option><option>Microperforado</option><option>Menú / PVC</option></select><label>Material</label><select id="material_id">${materials.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select><label>Anticipo USD</label><input id="deposit_usd" type="number" value="0" oninput="calc()"></div><div class="card wide"><h2>IA de vehículo</h2><label>Marca</label><input id="make" placeholder="Toyota"><label>Modelo</label><input id="model" placeholder="Corolla"><label>Año</label><input id="year" placeholder="2020"><label>Partes a rotular separadas por coma</label><input id="parts" value="capó, puerta izquierda, puerta derecha"><button onclick="estimateAI()">Estimar con IA</button><p class="hint">Las medidas son estimadas. Confirmar antes de imprimir o cortar.</p><div id="items"></div></div></div></section><aside class="card summary"><h2>Resumen</h2><div class="price" id="price">$0.00</div><b id="priceBs">Bs 0.00</b><div id="sum"></div><button onclick="saveQuote(false)">Guardar</button><button onclick="saveQuote(true)">Registrar venta</button></aside></div>`;calc()}
async function estimateAI(){try{const parts=$('parts').value.split(',').map(x=>x.trim()).filter(Boolean);const d=await api('/ai/estimate-vehicle',{method:'POST',body:JSON.stringify({make:$('make').value,model:$('model').value,year:$('year').value,parts,marginCm:Number(settings.waste_margin_cm)})});aiItems=d.parts.map(p=>({name:p.name,base_w:p.baseWidthCm,base_h:p.baseHeightCm,final_w:p.finalWidthCm,final_h:p.finalHeightCm,quantity:p.quantity||1,area_m2:p.areaM2,source:'ia',confidence:p.confidence||'media'}));renderItems();calc()}catch(e){toast(e.message)}}
function renderItems(){$('items').innerHTML=`<div class="table"><table><tr><th>Pieza</th><th>Base</th><th>Final</th><th>m²</th></tr>${aiItems.map(i=>`<tr><td>${i.name}<br><span class="badge">${i.confidence}</span></td><td>${i.base_w}x${i.base_h}</td><td>${i.final_w}x${i.final_h}</td><td>${Number(i.area_m2).toFixed(2)}</td></tr>`).join('')}</table></div>`}
function calc(){const mat=materials.find(m=>m.id===$('material_id')?.value)||materials[0];const total=aiItems.reduce((a,i)=>a+Number(i.area_m2||0),0);const internal=total*Number(mat?.cost_per_m2||0)+Number(settings?.design_base_cost||0)+Number(settings?.install_base_cost||0);const price=Math.max(internal/(1-Number(settings?.default_margin||.4)),Number(settings?.minimum_sale||25));const pricebs=price*Number(settings?.euro_bcv_rate||0);const deposit=Number($('deposit_usd')?.value||0);$('price').textContent=money(price);$('priceBs').textContent=bs(pricebs);$('sum').innerHTML=`<div class="row"><span>Material</span><b>${total.toFixed(2)} m²</b></div><div class="row"><span>Anticipo</span><b>${money(deposit)}</b></div><div class="row"><span>Saldo</span><b>${money(Math.max(price-deposit,0))}</b></div>${isAdmin()?`<div class="row"><span>Costo interno</span><b>${money(internal)}</b></div><div class="row"><span>Ganancia</span><b>${money(price-internal)}</b></div>`:''}`;return{total,internal,price,pricebs,deposit,balance:Math.max(price-deposit,0)}}
async function saveQuote(asOrder){try{if(!aiItems.length)return toast('Primero estima o agrega piezas.');const c=calc();const q=await api('/quotes',{method:'POST',body:JSON.stringify({client_name:$('client_name').value,client_phone:$('client_phone').value,business_name:$('business_name').value,sale_type:$('sale_type').value,material_id:$('material_id').value,total_m2:c.total,internal_cost:c.internal,price_usd:c.price,price_bs:c.pricebs,deposit_usd:c.deposit,balance_usd:c.balance,items:aiItems})});if(asOrder)await api(`/quotes/${q.id}/register-sale`,{method:'POST'});toast(asOrder?'Venta registrada':'Cotización guardada');show(asOrder?'orders':'dashboard')}catch(e){toast(e.message)}}
async function orders(){title('Órdenes y ventas','Seguimiento del flujo operativo.');const data=await api('/orders');$('content').innerHTML=`<section class="card full"><div class="table"><table><tr><th>Cliente</th><th>Trabajo</th><th>m²</th><th>Precio</th>${isAdmin()?'<th>Interno</th>':''}<th>Estado</th></tr>${data.map(o=>`<tr><td><b>${o.client_name}</b><br>${o.client_phone}</td><td>${o.sale_type}</td><td>${Number(o.total_m2).toFixed(2)}</td><td>${money(o.price_usd)}<br>${bs(o.price_bs)}</td>${isAdmin()?`<td>${money(o.internal_cost)}</td>`:''}<td><select onchange="statusOrder('${o.id}',this.value)">${['Venta registrada','Anticipo recibido','Diseño pendiente','Diseño en proceso','Diseño enviado','Diseño aprobado','En producción','Listo para instalar','Instalación programada','Instalado','Pagado completo','Finalizado','Cancelado'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</table></div></section>`}
async function statusOrder(id,status){await api('/orders/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})});toast('Estado actualizado')}
async function users(){title('Usuarios','Aprobación de solicitudes y jerarquías.');const data=await api('/users');$('content').innerHTML=`<section class="card full"><div class="table"><table><tr><th>Usuario</th><th>Solicita</th><th>Estado</th><th>Rol</th><th>Acciones</th></tr>${data.map(u=>`<tr><td><b>${u.name}</b><br>${u.email}</td><td>${u.requested_role}</td><td>${u.status}</td><td><select id="role-${u.id}"><option value="rotulador">Rotulador / Vendedor</option><option value="admin">Administrador</option></select></td><td>${u.status==='pending'?`<button onclick="approve('${u.id}')">Aprobar</button><button class="ghost" onclick="reject('${u.id}')">Rechazar</button>`:''}</td></tr>`).join('')}</table></div></section>`}
async function approve(id){await api('/users/'+id+'/approve',{method:'PATCH',body:JSON.stringify({role:$('role-'+id).value})});toast('Usuario aprobado');users()}
async function reject(id){await api('/users/'+id+'/reject',{method:'PATCH'});toast('Usuario rechazado');users()}
function config(){title('Precios y configuración','Tasa automática, materiales y margen.');$('content').innerHTML=`<div class="grid"><section class="card side"><h2>General</h2><label>Euro BCV</label><input id="rate" value="${settings.euro_bcv_rate}"><button onclick="updateBcv()">Actualizar Euro BCV automático</button><label>Margen %</label><input id="margin" value="${settings.default_margin*100}"><label>Margen cm por lado</label><input id="waste" value="${settings.waste_margin_cm}"><label>Diseño USD</label><input id="design" value="${settings.design_base_cost}"><label>Instalación USD</label><input id="install" value="${settings.install_base_cost}"><button onclick="saveConfig()">Guardar</button></section><section class="card wide"><h2>Materiales</h2><div class="table"><table><tr><th>Material</th><th>Costo</th><th>Venta</th><th></th></tr>${materials.map(m=>`<tr><td>${m.name}</td><td><input id="c-${m.id}" value="${m.cost_per_m2}"></td><td><input id="s-${m.id}" value="${m.sale_per_m2}"></td><td><button onclick="saveMat('${m.id}')">Guardar</button></td></tr>`).join('')}</table></div></section></div>`}
async function saveConfig(){settings=await api('/settings',{method:'PUT',body:JSON.stringify({euro_bcv_rate:Number($('rate').value),default_margin:Number($('margin').value)/100,waste_margin_cm:Number($('waste').value),design_base_cost:Number($('design').value),install_base_cost:Number($('install').value)})});toast('Configuración guardada')}
async function saveMat(id){await api('/settings/materials/'+id,{method:'PUT',body:JSON.stringify({cost_per_m2:Number($('c-'+id).value),sale_per_m2:Number($('s-'+id).value)})});await loadSettings();toast('Material actualizado')}
boot();
